#!/bin/bash

set -e
export $(cat .env | grep "#" -v)

./provition-DummySensorTTN
./subscribeQuantumTTN
echo -e "need to send Data from TTN console"
curl -X GET \
'http://localhost:'"${ORION_LD_PORT}"'/ngsi-ld/v1/subscriptions/' \
-H 'NGSILD-Tenant: openiot' |jq .
