#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#
set -e
export $(cat .env | grep "#" -v)



curl -G -X GET 'http://localhost:'"${ORION_LD_PORT}"'/ngsi-ld/v1/entities/urn:ngsi-ld:TemperatureSensor:temperaturesensor001' \
    -H 'fiware-service: openiot' \
    -H 'fiware-servicepath: /'  \
    -H 'Link: <http://context/ngsi-context.jsonld>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' | jq .
